package net.epam.study.controller.commands;

public enum CommandName {
	LOGINATION, REGISTRATION, SAVENEWUSER, GOTOLOGINPAGE, GOTOMAINPAGE,
	LOGOUT, CHECKLOGINANDPASSWORD, GOTOMENUPAGE, GOTOMAININDEXPAGE, ADDTOCART,
	GOTOBASKETPAGE, SAVENEWORDER, GOTOBILLPAGE, GOTOADMINPAGE, ORDERDELETE
}
