package net.epam.study.controller.command;

public enum CommandName {
	REGISTRATION, SAVENEWUSER, GOTOLOGINPAGE, GOTOMAINPAGE,
	LOGOUT, CHECKLOGINANDPASSWORD, GOTOMENUPAGE, GOTOMAININDEXPAGE, ADDTOCART,
	GOTOBASKETPAGE, SAVENEWORDER, GOTOBILLPAGE, GOTOADMINPAGE, ORDERDELETE,
	ITEMDELETE
}
