package net.epam.study.controller.command;

public enum CommandName {
	REGISTRATION, SAVENEWUSER, GOTOLOGINPAGE, GOTOMAINPAGE,
	LOGOUT, CHECKLOGINANDPASSWORD, GOTOMENUPAGE, ORDERSTATUS, ADDTOCART,
	GOTOBASKETPAGE, SAVENEWORDER, GOTOBILLPAGE, GOTOADMINPAGE, ORDERDELETE,
	ITEMDELETE,
}
